#!/bin/bash

USERID=$(id -u)
TIMESTAP=$(date +%F-%H:%M:%S)
SCRIPT_NAME=$($0 | cut -d "." -f1)




if [ $USERID -ne 0 ]
then
    echo "please run this script with root access"
    exit 1 #manulally exit if error comes
else   
    echo "Your are a super user"
fi





sudo yum install tree -y

if [ "$? ne 0" ]
then    
    echo "tree installation is failure"
    exit 1
else
    echo "tree installation is success"
fi

echo $TIMESTAMP